name: Package

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B install --file pom.xml

    - name: Rename GUI artifact
      run: mv vripper-gui/target/vripper-gui-*.jar vripper-gui/target/vripper-gui.jar

    - name: Rename WEB artifact
      run: mv vripper-web/target/vripper-web-*.jar vripper-web/target/vripper-web.jar

    - if: matrix.os == 'ubuntu-latest'
      name: Package Linux binaries
      run: |
        cd jpackage
        cp ../vripper-gui/target/vripper-gui.jar jar/vripper-gui.jar
        jpackage --type deb "@jpackage.cfg" "@jpackage-linux.cfg"
        jpackage --type rpm "@jpackage.cfg" "@jpackage-linux.cfg"
        ls -la dist

    - if: matrix.os == 'windows-latest'
      name: Package Windows binaries
      run: |
        cd jpackage
        cp ../vripper-gui/target/vripper-gui.jar jar/vripper-gui.jar
        jpackage "@jpackage.cfg" "@jpackage-windows.cfg"
        dir dist

    - if: matrix.os == 'macos-latest'
      name: Package macOS binaries
      run: |
        cd jpackage
        cp ../vripper-gui/target/vripper-gui.jar jar/vripper-gui.jar
        jpackage "@jpackage.cfg" "@jpackage-macos.cfg"
        ls -la dist
