name: Release

on:
  release:
    types: [created]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build parent project
      run: mvn -N -q install --file pom.xml

    - name: Build Core Jar
      run: mvn -B -q install --file vripper-core/pom.xml

    - name: Build GUI Jar
      run: mvn -B -q install --file vripper-gui/pom.xml

    - name: Rename GUI Jar
      run: mv vripper-gui/target/vripper-gui-${{ github.event.release.tag_name }}-jar-with-dependencies.jar vripper-gui/target/vripper-noarch-gui-${{ github.event.release.tag_name }}.jar

    - if: matrix.os == 'ubuntu-latest'
      name: Release GUI Jar
      uses: softprops/action-gh-release@v1
      with:
        files: vripper-gui/target/vripper-noarch-gui-${{ github.event.release.tag_name }}.jar

    # Start building WEB jar in ubuntu only
    - if: matrix.os == 'ubuntu-latest'
      name: Build WEB Jar
      run: |
        mvn -B -q install --file vripper-web-ui/pom.xml
        mvn -B -q install --file vripper-web/pom.xml

    - if: matrix.os == 'ubuntu-latest'
      name: Rename WEB Jar
      run: mv vripper-web/target/vripper-web-${{ github.event.release.tag_name }}.jar vripper-web/target/vripper-noarch-web-${{ github.event.release.tag_name }}.jar

    - if: matrix.os == 'ubuntu-latest'
      name: Release WEB Jar
      uses: softprops/action-gh-release@v1
      with:
        files: vripper-web/target/vripper-noarch-web-${{ github.event.release.tag_name }}.jar
    # End building WEB jar in ubuntu only

    - name: Prepare Packaging
      run: |
        cp vripper-gui/target/vripper-noarch-gui-${{ github.event.release.tag_name }}.jar jpackage/jar/vripper-gui.jar
        
    - if: matrix.os == 'ubuntu-latest'
      name: Package Linux
      run: |
        cd jpackage
        jpackage --app-version ${{ github.event.release.tag_name }} "@jpackage.cfg" "@jpackage-app-image.cfg" --icon icon.png
        jpackage --app-version ${{ github.event.release.tag_name }} "@jpackage.cfg" "@jpackage-linux.cfg" --type deb
        jpackage --app-version ${{ github.event.release.tag_name }} "@jpackage.cfg" "@jpackage-linux.cfg" --type rpm
        mv dist/vripper-${{ github.event.release.tag_name }}-1.x86_64.rpm dist/vripper-linux-${{ github.event.release.tag_name }}.x86_64.rpm
        mv dist/vripper_${{ github.event.release.tag_name }}-1_amd64.deb dist/vripper-linux-${{ github.event.release.tag_name }}_amd64.deb

    - if: matrix.os == 'windows-latest'
      name: Package Windows
      run: |
        cd jpackage
        jpackage --app-version ${{ github.event.release.tag_name }} "@jpackage.cfg" "@jpackage-app-image.cfg" --icon icon.ico
        jpackage --app-version ${{ github.event.release.tag_name }} "@jpackage.cfg" "@jpackage-windows.cfg" --type msi
        jpackage --app-version ${{ github.event.release.tag_name }} "@jpackage.cfg" "@jpackage-windows.cfg" --type exe
        cd dist
        ren VRipper-${{ github.event.release.tag_name }}.msi vripper-windows-installer-${{ github.event.release.tag_name }}.msi
        ren VRipper-${{ github.event.release.tag_name }}.exe vripper-windows-installer-${{ github.event.release.tag_name }}.exe

    - if: matrix.os == 'macos-latest'
      name: Package macOS
      run: |
        cd jpackage
        jpackage --app-version ${{ github.event.release.tag_name }} "@jpackage.cfg" "@jpackage-app-image.cfg" --icon icon.icns
        jpackage --app-version ${{ github.event.release.tag_name }} "@jpackage.cfg" "@jpackage-macos.cfg" --type pkg
        jpackage --app-version ${{ github.event.release.tag_name }} "@jpackage.cfg" "@jpackage-macos.cfg" --type dmg
        mv dist/VRipper-${{ github.event.release.tag_name }}.pkg dist/vripper-macos-${{ github.event.release.tag_name }}.pkg
        mv dist/VRipper-${{ github.event.release.tag_name }}.dmg dist/vripper-macos-${{ github.event.release.tag_name }}.dmg

    - if: matrix.os == 'ubuntu-latest'
      name: Zip Ubuntu portable
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        directory: 'jpackage/dist'
        path: 'VRipper'
        filename: 'vripper-linux-portable-${{ github.event.release.tag_name }}.zip'

    - if: matrix.os == 'windows-latest'
      name: Zip Windows portable
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        directory: 'jpackage/dist'
        path: 'VRipper'
        filename: 'vripper-windows-portable-${{ github.event.release.tag_name }}.zip'

    - if: matrix.os == 'macos-latest'
      name: Zip MacOS portable
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        directory: 'jpackage/dist'
        path: 'VRipper.app'
        filename: 'vripper-macos-portable-${{ github.event.release.tag_name }}.zip'

    - if: matrix.os == 'ubuntu-latest'
      name: Release packages for Linux
      uses: softprops/action-gh-release@v1
      with:
        files: |
          jpackage/dist/vripper-linux-${{ github.event.release.tag_name }}.x86_64.rpm
          jpackage/dist/vripper-linux-${{ github.event.release.tag_name }}_amd64.deb
          jpackage/dist/vripper-linux-portable-${{ github.event.release.tag_name }}.zip

    - if: matrix.os == 'windows-latest'
      name: Release packages for Windows
      uses: softprops/action-gh-release@v1
      with:
        files: |
          jpackage/dist/vripper-windows-installer-${{ github.event.release.tag_name }}.msi
          jpackage/dist/vripper-windows-installer-${{ github.event.release.tag_name }}.exe
          jpackage/dist/vripper-windows-portable-${{ github.event.release.tag_name }}.zip

    - if: matrix.os == 'macos-latest'
      name: Release packages for macOS
      uses: softprops/action-gh-release@v1
      with:
        files: |
          jpackage/dist/vripper-macos-${{ github.event.release.tag_name }}.pkg
          jpackage/dist/vripper-macos-${{ github.event.release.tag_name }}.dmg
          jpackage/dist/vripper-macos-portable-${{ github.event.release.tag_name }}.zip
